<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

		<title>{% block title %}{% endblock %}</title>
		<meta name="description" content="A jQuery widget for issuing HTTP requests, designed to help document and test APIs">
		<meta name="author" content="Mason Malone">
		<meta name="viewport" content="width=device-width">

		<link rel="stylesheet" href="css/bootswatch_spacelab.min.css">

		{% block head %}{% endblock %}
	</head>

	<body>
		{% block body %}{% endblock %}
	</body>
</html>
